title: The first of many Blogs
author: BAWhite92
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog that will be the start on my glorious journey to using GitHub efficiently and building my software development portfolio!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
